Testing with 1.2.8
nautobot/nautobot-plugin-workflow-dolt pull request #174
Opened 2022-03-09 23:20 UTC by nniehoff

2022-04-25 13:47 UTC, bryanculver commented
Please update: https://github.com/nautobot/nautobot-plugin-version-control/blob/6f7bc23e1f0efad9cf6bcaac520d99e13185b1c7/tasks.py#L29

2022-04-25 13:48 UTC, bryanculver requested changes

2022-04-25 13:48 UTC, bryanculver commented on .github/workflows/ci.yml
> +        nautobot-version: ["1.3.1"]
Please update

2023-05-24 14:18 UTC, itdependsnetworks commented
The next branch is based on nautobot 1.5, should not need this anymore.

2023-05-24 14:18 UTC, closed without merging